<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKizqwcr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKizqwcr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKizqwcr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKizqwcr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKizqwcr\appProdProjectContainer([
    'container.build_hash' => 'Kizqwcr',
    'container.build_id' => 'bc2c4330',
    'container.build_time' => 1635687301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKizqwcr');
