<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhhtqyq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhhtqyq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXhhtqyq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXhhtqyq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXhhtqyq\appDevDebugProjectContainer([
    'container.build_hash' => 'Xhhtqyq',
    'container.build_id' => '5490c2ee',
    'container.build_time' => 1635693727,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhhtqyq');
