<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container4hvq9jn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hvq9jn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4hvq9jn.legacy');
=======
if (\class_exists(\ContainerG3s06xc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3s06xc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerG3s06xc.legacy');
>>>>>>> origin/main

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container4hvq9jn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4hvq9jn\appProdProjectContainer([
    'container.build_hash' => '4hvq9jn',
    'container.build_id' => '039133c6',
    'container.build_time' => 1635689982,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4hvq9jn');
=======
    \class_alias(\ContainerG3s06xc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerG3s06xc\appProdProjectContainer([
    'container.build_hash' => 'G3s06xc',
    'container.build_id' => '62c814ae',
    'container.build_time' => 1634815360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3s06xc');
>>>>>>> origin/main
