<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4hvq9jn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hvq9jn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4hvq9jn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4hvq9jn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4hvq9jn\appProdProjectContainer([
    'container.build_hash' => '4hvq9jn',
    'container.build_id' => '039133c6',
    'container.build_time' => 1635689982,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4hvq9jn');
