<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEcdgpsr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEcdgpsr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEcdgpsr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEcdgpsr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEcdgpsr\appDevDebugProjectContainer([
    'container.build_hash' => 'Ecdgpsr',
    'container.build_id' => 'db45a050',
    'container.build_time' => 1635693733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEcdgpsr');
